volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      # device: /home/jbidaux/data/wordpress
      # device: /home/jbidaux/Documents/inception/src/wordpress
      # device: /media/sf_inception/wordpress
      device: /home/jbidaux/wordpress
      o: bind
      type: none
  mariadb-data:
    name: mariadb
    driver: local
    driver_opts:
      # device: /home/jbidaux/data/mariadb
      # device: /home/jbidaux/Documents/inception/src/mariadb
      # device: /media/sf_inception/mariadb
      device: /home/jbidaux/mariadb
      o: bind
      type: none

networks:
  inception:
    name: inception

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
    networks:
      - inception
    restart: always

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
    networks:
      - inception
    restart: always

  mariadb:
    build: ./requirements/mariadb/
    container_name: mariadb
    # ports:
    #   - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception
    restart: always
