services:
  nginx:
    build: ./requirements/nginx/.
    container_name: nginx
    ports: 
      - "8090:80" #this means that the port 8090 of the host is redirected to the port 80 inside the container
    volumes:
      - ./web:/var/www/html
    networks:
      - inception
    depends_on:
      - wordpress
    #   - mariadb
  wordpress:
    build: ./requirements/wordpress/.
    container_name: wp-php
    depends_on:
      - mariadb
    volumes:
      - ./web:/var/www/html
    #This line maps the ./web directory on the host machine to the 
    # /var/www/html directory inside the container. In that case here it is a bind mount
    #, the volume is shared from the host to the docker and is not a named volume managed
    #in the docker's storage area.
    networks:
      - inception
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/wp-admin/install.php"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s  # Gives more time before starting health checks
  mariadb:
    build:  ./requirements/mariadb/.
    container_name: mariadb
    volumes:
      - ./database:/var/lib/mysql
    networks:
      - inception

networks:
  inception: